title: Aldo Alberto Esquivel Gomez
logo: assets/portada/foto_centrada.png
description: ¡Saludos! Te doy la bienvenida a mi portafolio de proyectos de Análisis de Datos.
show_downloads: false
#google_analytics:
theme: jekyll-theme-minimal
